"""The knowledge write path: ``accept`` drafts, generate source ``sheet``s and ``harvest`` them.

Drafts are proposed new records in ``<root>/.knowledge/drafts/``. ``accept``
validates them in the post-acceptance world under the home lock and moves each
into ``entries/`` with ``os.link`` then ``os.unlink``, so an accepted record is
never overwritten. A sheet is a generated view of one source's records and
drafts; the only state read back from it is the checkbox of each draft row.
"""

from __future__ import annotations

import os
import re
from collections.abc import Iterable
from pathlib import Path
from typing import Any

from .home import (
    KNOWLEDGE_DIRECTORY,
    Base,
    DocumentType,
    Home,
    KnowledgeError,
    atomic_write_text,
    base_for_path,
    home_directory,
    load_home,
    lock,
)
from .index import name_key
from .records import (
    DRAFTS,
    ENTRIES,
    SHEETS,
    Files,
    Record,
    RecordError,
    fold,
    gloss,
    parse_record,
    parse_text,
    read_text,
    record_files,
    record_problems,
    source_lines,
)

SHEET_HEADER = "<!-- generated by kgd sheet; only draft checkboxes are read back -->"
TICKED_RE = re.compile(r"^- \[[xX]\] \[\[\.knowledge/drafts/(?P<id>[^|\]]+)(?:\|[^\]]*)?\]\]")
_DISPLAY_RE = re.compile(r"[|\[\]]")


def _realpath(path: Path | str) -> Path:
    return Path(os.path.realpath(Path(path).expanduser()))


def _knowledge(base: Base) -> Path:
    knowledge = base.root / KNOWLEDGE_DIRECTORY
    if knowledge.is_symlink():
        raise KnowledgeError(f"{knowledge} must not be a symlink")
    return knowledge


# ---------------------------------------------------------------- accept


def _locate_draft(home: Home, path: Path | str) -> tuple[Base | None, str, str | None]:
    """(base, id, problem) for one DRAFT argument."""
    real = _realpath(path)
    base = base_for_path(home.bases, real)
    if base is None:
        return None, "", f"{path} is not inside a registered base"
    if real.parent != base.root / KNOWLEDGE_DIRECTORY / DRAFTS or real.suffix != ".md":
        return base, "", f"{path} is not a {KNOWLEDGE_DIRECTORY}/{DRAFTS}/<id>.md file of base {base.name}"
    if (base.root / KNOWLEDGE_DIRECTORY).is_symlink():
        return base, "", f"{base.root / KNOWLEDGE_DIRECTORY} must not be a symlink"
    if not real.is_file():
        return base, "", f"{path} does not exist"
    return base, real.stem, None


def _understanding(path: Path, uid: str) -> str:
    try:
        return parse_record(path, uid.split(":", 1)[0]).understanding
    except (RecordError, OSError, UnicodeDecodeError):
        return "unknown"


def accept(paths: Iterable[Path | str], dry_run: bool = False) -> dict[str, Any]:
    """Promote drafts to accepted records, all or nothing.

    Returns ``{"refused": [{path, message}]}``, ``{"would_create": [uid]}`` for a
    dry run, or the receipt ``{"created": [uid], "understanding_set": [{uid, value}]}``.
    A receipt with ``aborted`` lists what was created before a target appeared.
    """
    home = load_home(home_directory())
    selected: list[tuple[Base, str, Path]] = []
    refused: list[dict[str, str]] = []
    seen: set[Path] = set()
    for argument in paths:
        base, identifier, problem = _locate_draft(home, argument)
        if problem is not None:
            refused.append({"path": str(_realpath(argument)), "message": problem})
            continue
        assert base is not None
        path = base.root / KNOWLEDGE_DIRECTORY / DRAFTS / f"{identifier}.md"
        if path not in seen:
            seen.add(path)
            selected.append((base, identifier, path))
    if refused:
        return {"refused": refused}
    with lock():
        files = Files(home)
        chosen: dict[str, set[str]] = {}
        for base, identifier, _ in selected:
            chosen.setdefault(base.name, set()).add(fold(identifier))
        plan: list[tuple[Path, Path, str, Record | None]] = []
        for base, identifier, path in selected:
            target = base.root / KNOWLEDGE_DIRECTORY / ENTRIES / f"{identifier}.md"
            try:
                text = read_text(path)
            except (OSError, UnicodeDecodeError) as error:
                refused.append({"path": str(path), "message": f"cannot read the draft: {error}"})
                continue
            existing = files.ids(base.name, ENTRIES).get(fold(identifier))
            if existing is not None:
                try:
                    identical = read_text(existing) == text
                except (OSError, UnicodeDecodeError):
                    identical = False
                if identical:
                    plan.append((path, existing, text, None))
                else:
                    refused.append({"path": str(path), "message": (
                        f"id {identifier} already exists in {ENTRIES}/; edit that record in place or choose a new id"
                    )})
                continue
            try:
                record = parse_text(text, base.name, identifier, path)
            except RecordError as error:
                refused.append({"path": str(path), "message": error.message})
                continue
            problems, freshness = record_problems(
                files, record, draft=True, linkable_drafts=chosen[base.name] - {fold(identifier)}
            )
            refused.extend({"path": str(path), "message": message} for _, message in problems)
            if freshness is not None and freshness[0] != "fresh":
                state, proposed = freshness
                where = f" (found at lines {proposed[0]}-{proposed[1]})" if proposed else ""
                refused.append({"path": str(path), "message": f"evidence is {state}{where}; the quotes must occur in the cited lines"})
            plan.append((path, target, text, record))
        if refused:
            return {"refused": refused}
        uids = [f"{base.name}:{identifier}" for base, identifier, _ in selected]
        if dry_run:
            return {"would_create": uids}
        created: list[str] = []
        understanding_set: list[dict[str, str]] = []
        for (path, target, text, record), uid in zip(plan, uids, strict=True):
            if record is not None:
                target.parent.mkdir(parents=True, exist_ok=True)
                try:
                    os.link(path, target)
                except FileExistsError:
                    try:
                        identical = read_text(target) == text
                    except (OSError, UnicodeDecodeError):
                        identical = False
                    if not identical:
                        return {
                            "created": created,
                            "understanding_set": understanding_set,
                            "aborted": {"path": str(path), "message": f"{target} appeared with different text; nothing was overwritten"},
                        }
            os.unlink(path)
            created.append(uid)
            understanding = record.understanding if record is not None else _understanding(target, uid)
            if understanding != "unknown":
                understanding_set.append({"uid": uid, "value": understanding})
    return {"created": created, "understanding_set": understanding_set}


# ---------------------------------------------------------------- sheet


def _source(home: Home, source: Path | str) -> tuple[Base, str, DocumentType]:
    real = _realpath(source)
    base = base_for_path(home.bases, real)
    if base is None:
        raise KnowledgeError(f"{source} is not inside a registered base")
    _knowledge(base)
    relative = real.relative_to(base.root).as_posix()
    if not real.is_file():
        raise KnowledgeError(f"{source} is not a file")
    return base, relative, base.type_of(relative)


def _records(base: Base, folder: str, relative: str) -> list[Record]:
    found = []
    for path in record_files(base.root, folder):
        try:
            record = parse_record(path, base.name)
        except (RecordError, OSError, UnicodeDecodeError):
            continue
        if record.source == relative:
            found.append(record)
    return sorted(found, key=lambda record: (record.lines[0], record.id))


def _display(files: Files, record: Record, uid: str) -> str:
    label = files.label(uid, drafts=True)
    if label is not None:
        return label
    base, identifier = uid.split(":", 1)
    return identifier if base == record.base else uid


def _roles(files: Files, record: Record) -> str:
    parts = []
    for role, values in record.roles:
        if values:
            shown = (_safe(value.term if value.uid is None else _display(files, record, value.uid)) for value in values)
            parts.append(f" · {role}: " + ", ".join(shown))
    return "".join(parts)


def _safe(label: str) -> str:
    return _DISPLAY_RE.sub(" ", label)


def _pending(records: list[Record]) -> list[tuple[str, str, list[tuple[Record, str]]]]:
    groups: dict[str, tuple[str, list[tuple[Record, str]]]] = {}
    for record in records:
        for role, _, value in record.values():
            if value.term is None:
                continue
            owners = groups.setdefault(name_key(value.term), (value.term, []))[1]
            if (record, role) not in owners:
                owners.append((record, role))
    return [(key, term, owners) for key, (term, owners) in sorted(groups.items())]


def _ticked(text: str) -> list[str]:
    """Draft ids of the ticked rows under ``## Drafts``, in row order."""
    ticked: dict[str, None] = {}
    section = None
    for line in text.split("\n"):
        if line.startswith("## "):
            section = line[3:].strip()
        elif section == "Drafts":
            match = TICKED_RE.match(line)
            if match:
                ticked[match.group("id")] = None
    return list(ticked)


def sheet_path(base: Base, relative: str) -> Path:
    return base.root / KNOWLEDGE_DIRECTORY / SHEETS / f"{relative}.md"


def render_sheet(home: Home, base: Base, relative: str, document_type: DocumentType, ticked: set[str]) -> str:
    files = Files(home)
    accepted = _records(base, ENTRIES, relative)
    drafts = _records(base, DRAFTS, relative)
    lines = [
        SHEET_HEADER,
        f"# {relative}",
        "",
        f"[[{relative}]] · type {document_type.name} · {len(accepted)} accepted · {len(drafts)} drafts",
        "",
    ]
    order = [*document_type.node_kinds, *document_type.relation_kinds]
    sections = [(kind, [record for record in accepted if record.kind == kind]) for kind in order]
    sections.append(("other", [record for record in accepted if record.kind not in order]))
    for kind, rows in sections:
        if not rows:
            continue
        lines.append(f"## {kind}")
        for record in rows:
            understanding = "" if record.understanding == "unknown" else f" · {record.understanding}"
            lines.append(
                f"- [[{KNOWLEDGE_DIRECTORY}/{ENTRIES}/{record.id}|{_safe(record.label)}]] · L{record.lines_text}"
                f"{understanding}{_roles(files, record)} — {gloss(record.body)}".rstrip()
            )
        lines.append("")
    pending = _pending(accepted)
    if pending:
        lines.append("## Pending")
        for _, term, owners in pending:
            lines.append(f"- {_safe(term)} — " + ", ".join(f"{_safe(record.label)} ({role})" for record, role in owners))
        lines.append("")
    if drafts:
        lines.append("## Drafts")
        for record in drafts:
            box = "x" if record.id in ticked else " "
            lines.append(
                f"- [{box}] [[{KNOWLEDGE_DIRECTORY}/{DRAFTS}/{record.id}|{_safe(record.label)}]] · {record.kind}"
                f" · L{record.lines_text}{_roles(files, record)} — {gloss(record.body)}".rstrip()
            )
        lines.append("")
    return "\n".join(lines).rstrip("\n") + "\n"


def _write_sheet(home: Home, base: Base, relative: str, document_type: DocumentType) -> Path:
    path = sheet_path(base, relative)
    ticked: set[str] = set()
    if path.is_file():
        try:
            ticked = set(_ticked(read_text(path)))
        except (OSError, UnicodeDecodeError):
            ticked = set()
    atomic_write_text(path, render_sheet(home, base, relative, document_type, ticked))
    return path


def sheet(source: Path | str) -> dict[str, str]:
    """Write ``<root>/.knowledge/sheets/<source path>.md``, keeping draft ticks."""
    home = load_home(home_directory())
    base, relative, document_type = _source(home, source)
    return {"sheet": str(_write_sheet(home, base, relative, document_type))}


def sheet_json(source: Path | str) -> dict[str, Any]:
    """The extraction profile and inventory of one source; writes nothing."""
    home = load_home(home_directory())
    base, relative, document_type = _source(home, source)
    accepted = _records(base, ENTRIES, relative)
    drafts = _records(base, DRAFTS, relative)
    return {
        "base": base.name,
        "source": relative,
        "type": document_type.name,
        "node_kinds": list(document_type.node_kinds),
        "relation_kinds": {kind: list(roles) for kind, roles in document_type.relation_kinds.items()},
        "epistemic": list(document_type.epistemic),
        "guidance": document_type.guidance,
        "line_count": len(source_lines(base.root / relative)),
        "records": [{
            "uid": record.uid,
            "label": record.label,
            "kind": record.kind,
            "class": record.class_,
            "lines": record.lines_text,
            "understanding": record.understanding,
            "gloss": gloss(record.body),
        } for record in accepted],
        "drafts": [{
            "id": record.id,
            "label": record.label,
            "kind": record.kind,
            "class": record.class_,
            "lines": record.lines_text,
        } for record in drafts],
        "pending": [{
            "term": term,
            "owners": [{"uid": record.uid, "role": role} for record, role in owners],
        } for _, term, owners in _pending(accepted)],
    }


# ---------------------------------------------------------------- harvest


def harvest(sheet: Path | str, dry_run: bool = False) -> dict[str, Any]:
    """Accept the ticked drafts of a sheet in one call, then regenerate the sheet."""
    home = load_home(home_directory())
    real = _realpath(sheet)
    base = base_for_path(home.bases, real)
    if base is None:
        raise KnowledgeError(f"{sheet} is not inside a registered base")
    sheets = _knowledge(base) / SHEETS
    if sheets not in real.parents or real.suffix != ".md":
        raise KnowledgeError(f"{sheet} is not a sheet under {sheets}")
    if not real.is_file():
        raise KnowledgeError(f"{sheet} does not exist")
    relative = real.relative_to(sheets).as_posix().removesuffix(".md")
    document_type = base.type_of(relative)
    drafts = base.root / KNOWLEDGE_DIRECTORY / DRAFTS
    selected = [drafts / f"{identifier}.md" for identifier in _ticked(read_text(real))]
    receipt = accept([path for path in selected if path.is_file()], dry_run)
    if "created" in receipt and "aborted" not in receipt:
        _write_sheet(home, base, relative, document_type)
    return receipt
