from __future__ import annotations

import runpy
import unittest
from pathlib import Path, PurePosixPath

REPO_ROOT = Path(__file__).resolve().parents[1]
CHECKER = runpy.run_path(str(REPO_ROOT / "scripts" / "check_distribution.py"))


class DistributionInventoryTest(unittest.TestCase):
    def test_installed_product_contains_the_omp_extension_and_instructions(self) -> None:
        wheel, sdist = CHECKER["_expected_product_files"]()
        self.assertIn("kgdistiller/product/integrations/omp/compiled_tools.ts", wheel)
        self.assertIn("kgdistiller/product/docs/omp-compiled-tools.md", wheel)
        self.assertIn("integrations/omp/compiled_tools.ts", sdist)
        self.assertIn("docs/omp-compiled-tools.md", sdist)

    def test_distribution_inventory_ignores_python_bytecode_caches(self) -> None:
        product_cache = (
            REPO_ROOT
            / "skills"
            / "capture-kgdistiller"
            / "__pycache__"
        )
        package_cache = REPO_ROOT / "src" / "kgdistiller" / "adapters" / "__pycache__"
        product_probe = product_cache / "distribution-regression.cpython-313.pyc"
        package_probe = package_cache / "distribution-regression.cpython-313.pyc"
        for cache, probe in (
            (product_cache, product_probe),
            (package_cache, package_probe),
        ):
            cache.mkdir(exist_ok=True)
            probe.write_bytes(b"generated bytecode probe")
        try:
            package = CHECKER["_expected_package_files"]()
            wheel, sdist = CHECKER["_expected_product_files"]()
        finally:
            for cache, probe in (
                (product_cache, product_probe),
                (package_cache, package_probe),
            ):
                probe.unlink(missing_ok=True)
                try:
                    cache.rmdir()
                except OSError:
                    pass

        wheel_path = PurePosixPath(
            "kgdistiller/product/skills/capture-kgdistiller/"
            "__pycache__/distribution-regression.cpython-313.pyc"
        ).as_posix()
        source_path = PurePosixPath(
            "skills/capture-kgdistiller/__pycache__/"
            "distribution-regression.cpython-313.pyc"
        ).as_posix()
        package_path = PurePosixPath(
            "kgdistiller/adapters/__pycache__/"
            "distribution-regression.cpython-313.pyc"
        ).as_posix()
        self.assertNotIn(package_path, package)
        self.assertNotIn(wheel_path, wheel)
        self.assertNotIn(source_path, sdist)


if __name__ == "__main__":
    unittest.main()
