import { App, Platform, Plugin, PluginSettingTab, Setting } from "obsidian";

import type { HiddenKnowledgeStatus } from "./hidden-knowledge";

export interface KgdistillerSettings {
  graphPath: string;
  showSources: boolean;
  showDefinitions: boolean;
  showReferences: boolean;
  hiddenKnowledgeEnabled: boolean;
  hiddenKnowledgeFolder: string;
}

export const DEFAULT_SETTINGS: KgdistillerSettings = {
  graphPath: "knowledge/build/obsidian/semantic-graph.json",
  showSources: true,
  showDefinitions: true,
  showReferences: true,
  hiddenKnowledgeEnabled: false,
  hiddenKnowledgeFolder: ".knowledge",
};

export interface SettingsHost {
  settings: KgdistillerSettings;
  hiddenKnowledgeStatus: HiddenKnowledgeStatus;
  savePluginSettings(): Promise<void>;
  refreshGraphViews(): Promise<void>;
  rescanHiddenKnowledge(): Promise<void>;
}

export class KgdistillerSettingTab extends PluginSettingTab {
  private hiddenStatusSetting?: Setting;
  constructor(app: App, private readonly host: SettingsHost & Plugin) {
    super(app, host);
  }

  display(): void {
    const { containerEl } = this;
    containerEl.empty();
    new Setting(containerEl).setName("Graph data").setHeading();

    new Setting(containerEl)
      .setName("Semantic graph path")
      .setDesc("Vault-relative path generated by `kgdistiller export obsidian`.")
      .addText((text) =>
        text
          .setPlaceholder(DEFAULT_SETTINGS.graphPath)
          .setValue(this.host.settings.graphPath)
          .onChange(async (value) => {
            this.host.settings.graphPath = value.trim() || DEFAULT_SETTINGS.graphPath;
            await this.host.savePluginSettings();
            await this.host.refreshGraphViews();
          }),
      );

    new Setting(containerEl)
      .setName("Show source nodes")
      .setDesc("Display registered authority files alongside concepts.")
      .addToggle((toggle) =>
        toggle.setValue(this.host.settings.showSources).onChange(async (value) => {
          this.host.settings.showSources = value;
          await this.host.savePluginSettings();
          await this.host.refreshGraphViews();
        }),
      );

    new Setting(containerEl)
      .setName("Show definition edges")
      .setDesc("Display source → concept edges for authoritative definitions.")
      .addToggle((toggle) =>
        toggle.setValue(this.host.settings.showDefinitions).onChange(async (value) => {
          this.host.settings.showDefinitions = value;
          await this.host.savePluginSettings();
          await this.host.refreshGraphViews();
        }),
      );

    new Setting(containerEl)
      .setName("Show reference edges")
      .setDesc("Display source → concept edges for ordinary source references.")
      .addToggle((toggle) =>
        toggle.setValue(this.host.settings.showReferences).onChange(async (value) => {
          this.host.settings.showReferences = value;
          await this.host.savePluginSettings();
          await this.host.refreshGraphViews();
        }),
      );

    new Setting(containerEl).setName("Hidden knowledge folder").setHeading();
    new Setting(containerEl)
      .setName("Index hidden knowledge folder")
      .setDesc("On desktop, include this folder in native editing, links, backlinks, search and graph indexing. Uses internal Obsidian APIs; incompatible versions are reported below.")
      .addToggle((toggle) =>
        toggle
          .setValue(this.host.settings.hiddenKnowledgeEnabled)
          .setDisabled(Platform.isMobile)
          .onChange(async (value) => {
            this.host.settings.hiddenKnowledgeEnabled = value;
            await this.host.savePluginSettings();
            this.refreshHiddenKnowledgeStatus();
          }),
      );

    let folder = this.host.settings.hiddenKnowledgeFolder;
    new Setting(containerEl)
      .setName("Hidden folder path")
      .setDesc("Vault-relative hidden folder. Applying this setting changes indexing only; it does not move knowledge data or change the semantic graph path.")
      .addText((text) =>
        text
          .setPlaceholder(DEFAULT_SETTINGS.hiddenKnowledgeFolder)
          .setValue(folder)
          .setDisabled(Platform.isMobile)
          .onChange((value) => { folder = value.trim(); }),
      )
      .addButton((button) =>
        button
          .setButtonText("Apply")
          .setDisabled(Platform.isMobile)
          .onClick(async () => {
            this.host.settings.hiddenKnowledgeFolder = folder;
            await this.host.savePluginSettings();
            this.refreshHiddenKnowledgeStatus();
          }),
      );

    this.hiddenStatusSetting = new Setting(containerEl)
      .setName("Indexing status")
      .addButton((button) =>
        button
          .setButtonText("Rescan")
          .setDisabled(Platform.isMobile)
          .onClick(async () => {
            await this.host.rescanHiddenKnowledge();
            this.refreshHiddenKnowledgeStatus();
          }),
      );
    this.refreshHiddenKnowledgeStatus();
  }

  refreshHiddenKnowledgeStatus(): void {
    const status = this.host.hiddenKnowledgeStatus;
    const messages: Record<HiddenKnowledgeStatus["state"], string> = {
      disabled: "Disabled. Hidden knowledge files are not indexed by this plugin.",
      enabled: `Indexed: ${status.root}.`,
      missing: `Folder not found: ${status.root}. Create it, then rescan.`,
      unsupported: "Hidden folder indexing is unavailable in this environment.",
      invalid: "The hidden folder path is invalid.",
      error: "Hidden folder indexing failed.",
      disposed: "Hidden folder indexing has stopped.",
    };
    this.hiddenStatusSetting?.setDesc(status.message || messages[status.state]);
  }
}
