import { App, Plugin, PluginSettingTab, Setting } from "obsidian";

export interface KgdistillerSettings {
  graphPath: string;
  showSources: boolean;
  showDefinitions: boolean;
  showReferences: boolean;
}

export const DEFAULT_SETTINGS: KgdistillerSettings = {
  graphPath: "knowledge/build/obsidian/semantic-graph.json",
  showSources: true,
  showDefinitions: true,
  showReferences: true,
};

export interface SettingsHost {
  settings: KgdistillerSettings;
  savePluginSettings(): Promise<void>;
  refreshGraphViews(): Promise<void>;
}

export class KgdistillerSettingTab extends PluginSettingTab {
  constructor(app: App, private readonly host: SettingsHost & Plugin) {
    super(app, host);
  }

  display(): void {
    const { containerEl } = this;
    containerEl.empty();
    containerEl.createEl("h2", { text: "kgdistiller graph" });

    new Setting(containerEl)
      .setName("Semantic graph path")
      .setDesc("Vault-relative path generated by `kgdistiller export obsidian`.")
      .addText((text) =>
        text
          .setPlaceholder(DEFAULT_SETTINGS.graphPath)
          .setValue(this.host.settings.graphPath)
          .onChange(async (value) => {
            this.host.settings.graphPath = value.trim() || DEFAULT_SETTINGS.graphPath;
            await this.host.savePluginSettings();
            await this.host.refreshGraphViews();
          }),
      );

    new Setting(containerEl)
      .setName("Show source nodes")
      .setDesc("Display registered authority files alongside concepts.")
      .addToggle((toggle) =>
        toggle.setValue(this.host.settings.showSources).onChange(async (value) => {
          this.host.settings.showSources = value;
          await this.host.savePluginSettings();
          await this.host.refreshGraphViews();
        }),
      );

    new Setting(containerEl)
      .setName("Show definition edges")
      .setDesc("Display source → concept edges for authoritative definitions.")
      .addToggle((toggle) =>
        toggle.setValue(this.host.settings.showDefinitions).onChange(async (value) => {
          this.host.settings.showDefinitions = value;
          await this.host.savePluginSettings();
          await this.host.refreshGraphViews();
        }),
      );

    new Setting(containerEl)
      .setName("Show reference edges")
      .setDesc("Display source → concept edges for ordinary source references.")
      .addToggle((toggle) =>
        toggle.setValue(this.host.settings.showReferences).onChange(async (value) => {
          this.host.settings.showReferences = value;
          await this.host.savePluginSettings();
          await this.host.refreshGraphViews();
        }),
      );
  }
}
